// INCLUDE FILE generated by "Pelles C for Windows, version 9.00".

#define MAINMENU		2001

// AMM -- application main menu
#define AMM_OPENFILE		6002
#define AMM_SAVEFILEAS		6004
#define AMM_COPY			7001
#define AMM_DELETE			7002
#define AMM_PASTE			7003
#define AMM_SELECTALL		7004
#define AMM_MAKESILENT		7005
#define AMM_SAVESELECTED	7006
#define AMM_REVERSESELECTED	7007
#define AMM_ABOUT			8001
